# Name of your site (displayed in the header)
name: Random notes

# Short bio or description (displayed in the header)
description: This page is my notes about what I learned. They are mostly technical stuffs that are not easy to represent in standard blogging system.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
